# Generated by Django 4.2.2 on 2023-10-18 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Produto',
            new_name='Task',
        ),
    ]
